FROM ubuntu:20.04

# Install Java
RUN apt-get update && apt-get install -y openjdk-17-jdk

# Install Python
RUN apt-get install -y python3 python3-pip

# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y nodejs

# Install GCC (C/C++)
RUN apt-get install -y build-essential

# Install PHP
RUN apt-get install -y php-cli

# Set default working directory
WORKDIR /workspace
